name: TranslationManager
version: "1.0"
description: Import and export translations
url: https://github.com/mattias-persson/statamic-translation-manager
developer: Mattias Persson
developer_url: https://happypixels.se
