name: TranslationManager
version: '2.2.0'
description: 'Import and export translatable content'
url: 'https://statamic.com/marketplace/addons/translation-manager'
developer: 'Mattias Persson'
developer_url: 'https://happypixels.se'
