name: TranslationManager
version: '2.1.1'
description: 'Import and export translatable content'
url: 'https://statamic.com/marketplace/addons/translation-manager'
developer: 'Mattias Persson'
developer_url: 'https://happypixels.se'
